basePath: /api
definitions:
  internal_profile.loginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  internal_profile.registerRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  internal_profile.registerResponse:
    properties:
      email:
        type: string
      expires_at:
        type: string
      id:
        type: string
      token:
        type: string
    type: object
  internal_profile.tokenResponse:
    properties:
      expires_at:
        type: string
      token:
        type: string
    type: object
  internal_profile.userResponse:
    properties:
      email:
        type: string
      id:
        type: string
    type: object
info:
  contact: {}
  description: User registration, login, and profile.
  title: Omni Profile API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Email and password
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/internal_profile.loginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_profile.tokenResponse'
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Log in
      tags:
      - auth
  /auth/me:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_profile.userResponse'
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get current user
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Email and password
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/internal_profile.registerRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/internal_profile.registerResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: Conflict
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new user
      tags:
      - auth
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
